// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20221102184529_more-seed-data")]
    partial class moreseeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DishGroup")
                        .HasColumnType("int");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Botanist gin, Campari, Vermouth Di Torino",
                            DishGroup = 6,
                            ImgPath = "/img/menu/NEGRONI.jpg",
                            Name = "NEGRONI",
                            Price = 1m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tanqueray London Dry gin, Noilly Prat dry vermouth",
                            DishGroup = 6,
                            ImgPath = "/img/menu/martini.jpg",
                            Name = "MARTINI",
                            Price = 2m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sazerac Rye whiskey, Cocchi Vermouth Di Torino",
                            DishGroup = 6,
                            ImgPath = "/img/menu/manhattan.jpg",
                            Name = "MANHATTAN",
                            Price = 3m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Four Roses Yellow Label bourbon, lemon",
                            DishGroup = 6,
                            ImgPath = "/img/menu/whiskey_sour.jpg",
                            Name = "WHISKEY SOUR",
                            Price = 4m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Buffalo Trace bourbon, demerara, Angostura Bitters",
                            DishGroup = 6,
                            ImgPath = "/img/menu/OLD_FASHIONED.jpg",
                            Name = "OLD FASHIONED",
                            Price = 5m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Grey Goose vodka, tomato juice, lemon, celery, olives, Fridays® seasoning. Served with the usual accompaniments.",
                            DishGroup = 6,
                            ImgPath = "/img/menu/BLOODY_MARY.jpg",
                            Name = "BLOODY MARY",
                            Price = 6m
                        },
                        new
                        {
                            Id = 7,
                            Description = "The microwave is a great way to reheat stuffed mushrooms because it's gentle and it doesn't dry them out. Plus, it's a quick and easy way to heat them up without having to use the oven or the stovetop.",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Roasted_stuffed_mushrooms.jpg",
                            Name = "Roasted stuffed mushrooms",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Roll each wrapper on the diagonal to enclose filling, folding in sides after first complete turn. Place spring rolls on prepared trays, seam-side down; brush",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Baked_spring_rolls.jpg",
                            Name = "Baked spring rolls",
                            Price = 18.50m
                        },
                        new
                        {
                            Id = 9,
                            Description = "This contemporary take on beef Wellington reimagines pastry-wrapped tenderloin as a tart, showcasing flavors both comforting and complex.",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Baked_spring_rolls.jpg",
                            Name = "Baked spring rolls",
                            Price = 7.05m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Creamy pan-fried feta cheese with a golden crust is a delicious ... With the salty feta and sweet honey on top, this feta saganaki ",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Sweet_fried_saganaki.jpg",
                            Name = "Sweet fried saganaki",
                            Price = 29.95m
                        },
                        new
                        {
                            Id = 11,
                            Description = "If you fancy making yourself a little treat, try these tasty bacon wrapped onion rings. We replaced the traditional breadcrumbs with streaky bacon",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Bacon_rings.jpg",
                            Name = "Bacon rings",
                            Price = 38.51m
                        },
                        new
                        {
                            Id = 12,
                            Description = "A blooming onion, also called onion bloom, onion blossom, onion flower, bloomin' onion, or onion mum, is a dish consisting of one large onion",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Blooming_onion.jpg",
                            Name = "Blooming onion",
                            Price = 10.30m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Calzones are Italian turnovers that are stuffed with an array of ingredients. Pretty much anything that goes on a pizza can go into a calzone",
                            DishGroup = 9,
                            ImgPath = "/img/menu/CALZONES.jpg",
                            Name = "CALZONES",
                            Price = 27.95m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Deep Fried Main Dishes. Fried chicken. Fish Tacos. Corn dogs. Finger Steaks. When you're in the mood for crispy fried food, these 5-star recipes do it right",
                            DishGroup = 9,
                            ImgPath = "/img/menu/DEEP_FRIED_MAIN_DISHES.jpg",
                            Name = "Deep Fried Main Dishes",
                            Price = 35.95m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Ground beef or a mix of ground beef, pork and sometimes veal or venison, finely chopped (fried) onions, some broth, often with cream and sometimes with breadcrumbs soaked in milk",
                            DishGroup = 9,
                            ImgPath = "/img/menu/MEATBALLS.jpg",
                            Name = "MEATBALLS",
                            Price = 33.95m
                        },
                        new
                        {
                            Id = 16,
                            Description = "A pielike dish consisting of an unsweetened pastry shell filled with a custard and usually containing cheese and other ingredients, as vegetables, seafood",
                            DishGroup = 9,
                            ImgPath = "/img/menu/QUICHE.jpg",
                            Name = "QUICHE",
                            Price = 11.95m
                        },
                        new
                        {
                            Id = 17,
                            Description = "We've rounded up our 60 best chicken breast recipes, all of which are pretty easy, ... An easy, cheesy chicken breast supper that's as basic as they come",
                            DishGroup = 9,
                            ImgPath = "/img/menu/CHICKEN_MAIN_DISHES.jpg",
                            Name = "CHICKEN MAIN DISHES",
                            Price = 22.95m
                        },
                        new
                        {
                            Id = 18,
                            Description = "From seafood pastas and paellas, to creamy chowders and curries, our seafood recipes celebrate prawns, crab, clams, mussels and more.",
                            DishGroup = 9,
                            ImgPath = "/img/menu/SEAFOOD_MAIN_DISHES.jpg",
                            Name = "SEAFOOD MAIN DISHES",
                            Price = 11.95m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Tiramisu cake is made of moist and fluffy vanilla layers soaked with a mixture of brandy, coffee liqueur and espresso",
                            DishGroup = 2,
                            ImgPath = "/img/menu/TIRAMISU_LAYER_CAKE.jpg",
                            Name = "TIRAMISU LAYER CAKE",
                            Price = 18.95m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Devil's Food Cake is a variety of chocolate cake that uses cocoa powder instead of melted chocolate which is found in many chocolate cake recipes.",
                            DishGroup = 2,
                            ImgPath = "/img/menu/DEVIL'S_FOOD_CAKE.jpg",
                            Name = "DEVIL'S FOOD CAKE",
                            Price = 15.95m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Lemon Soufflés are made with only three ingredients: lemons, sugar, and eggs. They are so simple but so delicous and make a big impact when served in lemon juice",
                            DishGroup = 2,
                            ImgPath = "/img/menu/LEMON_SOUFFLES.jpg ",
                            Name = "LEMON SOUFFLES",
                            Price = 22.95m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Baklava is a layered pastry dessert made of filo pastry, filled with chopped nuts, and sweetened with syrup or honey ",
                            DishGroup = 2,
                            ImgPath = "/img/menu/BAKLAVA.jpg",
                            Name = "BAKLAVA",
                            Price = 11.95m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Our classic 8'' doberge cakes boast six layers of rich buttermilk cake sandwiching our handmade custard, frosted with our creamy buttercream, ",
                            DishGroup = 2,
                            ImgPath = "/img/menu/LEMON_CAKE_DOBERGE.jpg ",
                            Name = "LEMON CAKE DOBERGE",
                            Price = 33.95m
                        },
                        new
                        {
                            Id = 24,
                            Description = "In a saucepan, combine the chocolate, milk and cream and heat on low, stirring often, until the chocolate is completely melted and the mixture ",
                            DishGroup = 2,
                            ImgPath = "/img/menu/CHOCOLATE_FONDUE.jpg ",
                            Name = "CHOCOLATE FONDUE",
                            Price = 44.95m
                        },
                        new
                        {
                            Id = 25,
                            Description = "The Botanist gin, Campari, Vermouth Di Torino",
                            DishGroup = 6,
                            ImgPath = "/img/menu/NEGRONI.jpg",
                            Name = "NEGRONI",
                            Price = 25m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Tanqueray London Dry gin, Noilly Prat dry vermouth",
                            DishGroup = 6,
                            ImgPath = "/img/menu/martini.jpg",
                            Name = "MARTINI",
                            Price = 26m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Sazerac Rye whiskey, Cocchi Vermouth Di Torino",
                            DishGroup = 6,
                            ImgPath = "/img/menu/manhattan.jpg",
                            Name = "MANHATTAN",
                            Price = 27m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Four Roses Yellow Label bourbon, lemon",
                            DishGroup = 6,
                            ImgPath = "/img/menu/whiskey_sour.jpg",
                            Name = "WHISKEY SOUR",
                            Price = 28m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Buffalo Trace bourbon, demerara, Angostura Bitters",
                            DishGroup = 6,
                            ImgPath = "/img/menu/OLD_FASHIONED.jpg",
                            Name = "OLD FASHIONED",
                            Price = 29m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Grey Goose vodka, tomato juice, lemon, celery, olives, Fridays® seasoning. Served with the usual accompaniments.",
                            DishGroup = 6,
                            ImgPath = "/img/menu/BLOODY_MARY.jpg",
                            Name = "BLOODY MARY",
                            Price = 30m
                        },
                        new
                        {
                            Id = 31,
                            Description = "The microwave is a great way to reheat stuffed mushrooms because it's gentle and it doesn't dry them out. Plus, it's a quick and easy way to heat them up without having to use the oven or the stovetop.",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Roasted_stuffed_mushrooms.jpg",
                            Name = "Roasted stuffed mushrooms",
                            Price = 31m
                        },
                        new
                        {
                            Id = 32,
                            Description = "Roll each wrapper on the diagonal to enclose filling, folding in sides after first complete turn. Place spring rolls on prepared trays, seam-side down; brush",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Baked_spring_rolls.jpg",
                            Name = "Baked spring rolls",
                            Price = 32m
                        },
                        new
                        {
                            Id = 33,
                            Description = "This contemporary take on beef Wellington reimagines pastry-wrapped tenderloin as a tart, showcasing flavors both comforting and complex.",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Baked_spring_rolls.jpg",
                            Name = "Baked spring rolls",
                            Price = 33m
                        },
                        new
                        {
                            Id = 34,
                            Description = "Creamy pan-fried feta cheese with a golden crust is a delicious ... With the salty feta and sweet honey on top, this feta saganaki ",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Sweet_fried_saganaki.jpg",
                            Name = "Sweet fried saganaki",
                            Price = 34m
                        },
                        new
                        {
                            Id = 35,
                            Description = "If you fancy making yourself a little treat, try these tasty bacon wrapped onion rings. We replaced the traditional breadcrumbs with streaky bacon",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Bacon_rings.jpg",
                            Name = "Bacon rings",
                            Price = 35m
                        },
                        new
                        {
                            Id = 36,
                            Description = "A blooming onion, also called onion bloom, onion blossom, onion flower, bloomin' onion, or onion mum, is a dish consisting of one large onion",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Blooming_onion.jpg",
                            Name = "Blooming onion",
                            Price = 36m
                        },
                        new
                        {
                            Id = 37,
                            Description = "Calzones are Italian turnovers that are stuffed with an array of ingredients. Pretty much anything that goes on a pizza can go into a calzone",
                            DishGroup = 9,
                            ImgPath = "/img/menu/CALZONES.jpg",
                            Name = "CALZONES",
                            Price = 37m
                        },
                        new
                        {
                            Id = 38,
                            Description = "Deep Fried Main Dishes. Fried chicken. Fish Tacos. Corn dogs. Finger Steaks. When you're in the mood for crispy fried food, these 5-star recipes do it right",
                            DishGroup = 9,
                            ImgPath = "/img/menu/DEEP_FRIED_MAIN_DISHES.jpg",
                            Name = "Deep Fried Main Dishes",
                            Price = 38m
                        },
                        new
                        {
                            Id = 39,
                            Description = "Ground beef or a mix of ground beef, pork and sometimes veal or venison, finely chopped (fried) onions, some broth, often with cream and sometimes with breadcrumbs soaked in milk",
                            DishGroup = 9,
                            ImgPath = "/img/menu/MEATBALLS.jpg",
                            Name = "MEATBALLS",
                            Price = 39m
                        },
                        new
                        {
                            Id = 40,
                            Description = "A pielike dish consisting of an unsweetened pastry shell filled with a custard and usually containing cheese and other ingredients, as vegetables, seafood",
                            DishGroup = 9,
                            ImgPath = "/img/menu/QUICHE.jpg",
                            Name = "QUICHE",
                            Price = 40m
                        },
                        new
                        {
                            Id = 41,
                            Description = "We've rounded up our 60 best chicken breast recipes, all of which are pretty easy, ... An easy, cheesy chicken breast supper that's as basic as they come",
                            DishGroup = 9,
                            ImgPath = "/img/menu/CHICKEN_MAIN_DISHES.jpg",
                            Name = "CHICKEN MAIN DISHES",
                            Price = 41m
                        },
                        new
                        {
                            Id = 42,
                            Description = "From seafood pastas and paellas, to creamy chowders and curries, our seafood recipes celebrate prawns, crab, clams, mussels and more.",
                            DishGroup = 9,
                            ImgPath = "/img/menu/SEAFOOD_MAIN_DISHES.jpg",
                            Name = "SEAFOOD MAIN DISHES",
                            Price = 42m
                        },
                        new
                        {
                            Id = 43,
                            Description = "Tiramisu cake is made of moist and fluffy vanilla layers soaked with a mixture of brandy, coffee liqueur and espresso",
                            DishGroup = 2,
                            ImgPath = "/img/menu/TIRAMISU_LAYER_CAKE.jpg",
                            Name = "TIRAMISU LAYER CAKE",
                            Price = 43m
                        },
                        new
                        {
                            Id = 44,
                            Description = "Devil's Food Cake is a variety of chocolate cake that uses cocoa powder instead of melted chocolate which is found in many chocolate cake recipes.",
                            DishGroup = 2,
                            ImgPath = "/img/menu/DEVIL'S_FOOD_CAKE.jpg",
                            Name = "DEVIL'S FOOD CAKE",
                            Price = 44m
                        },
                        new
                        {
                            Id = 45,
                            Description = "Lemon Soufflés are made with only three ingredients: lemons, sugar, and eggs. They are so simple but so delicous and make a big impact when served in lemon juice",
                            DishGroup = 2,
                            ImgPath = "/img/menu/LEMON_SOUFFLES.jpg ",
                            Name = "LEMON SOUFFLES",
                            Price = 45m
                        },
                        new
                        {
                            Id = 46,
                            Description = "Baklava is a layered pastry dessert made of filo pastry, filled with chopped nuts, and sweetened with syrup or honey ",
                            DishGroup = 2,
                            ImgPath = "/img/menu/BAKLAVA.jpg",
                            Name = "BAKLAVA",
                            Price = 46m
                        },
                        new
                        {
                            Id = 47,
                            Description = "Our classic 8'' doberge cakes boast six layers of rich buttermilk cake sandwiching our handmade custard, frosted with our creamy buttercream, ",
                            DishGroup = 2,
                            ImgPath = "/img/menu/LEMON_CAKE_DOBERGE.jpg ",
                            Name = "LEMON CAKE DOBERGE",
                            Price = 47m
                        },
                        new
                        {
                            Id = 48,
                            Description = "In a saucepan, combine the chocolate, milk and cream and heat on low, stirring often, until the chocolate is completely melted and the mixture ",
                            DishGroup = 2,
                            ImgPath = "/img/menu/CHOCOLATE_FONDUE.jpg ",
                            Name = "CHOCOLATE FONDUE",
                            Price = 48m
                        },
                        new
                        {
                            Id = 49,
                            Description = "The Botanist gin, Campari, Vermouth Di Torino",
                            DishGroup = 6,
                            ImgPath = "/img/menu/NEGRONI.jpg",
                            Name = "NEGRONI",
                            Price = 49m
                        },
                        new
                        {
                            Id = 50,
                            Description = "Tanqueray London Dry gin, Noilly Prat dry vermouth",
                            DishGroup = 6,
                            ImgPath = "/img/menu/martini.jpg",
                            Name = "MARTINI",
                            Price = 50m
                        },
                        new
                        {
                            Id = 51,
                            Description = "Sazerac Rye whiskey, Cocchi Vermouth Di Torino",
                            DishGroup = 6,
                            ImgPath = "/img/menu/manhattan.jpg",
                            Name = "MANHATTAN",
                            Price = 51m
                        },
                        new
                        {
                            Id = 52,
                            Description = "Four Roses Yellow Label bourbon, lemon",
                            DishGroup = 6,
                            ImgPath = "/img/menu/whiskey_sour.jpg",
                            Name = "WHISKEY SOUR",
                            Price = 52m
                        },
                        new
                        {
                            Id = 53,
                            Description = "Buffalo Trace bourbon, demerara, Angostura Bitters",
                            DishGroup = 6,
                            ImgPath = "/img/menu/OLD_FASHIONED.jpg",
                            Name = "OLD FASHIONED",
                            Price = 53m
                        },
                        new
                        {
                            Id = 54,
                            Description = "Grey Goose vodka, tomato juice, lemon, celery, olives, Fridays® seasoning. Served with the usual accompaniments.",
                            DishGroup = 6,
                            ImgPath = "/img/menu/BLOODY_MARY.jpg",
                            Name = "BLOODY MARY",
                            Price = 54m
                        },
                        new
                        {
                            Id = 55,
                            Description = "The microwave is a great way to reheat stuffed mushrooms because it's gentle and it doesn't dry them out. Plus, it's a quick and easy way to heat them up without having to use the oven or the stovetop.",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Roasted_stuffed_mushrooms.jpg",
                            Name = "Roasted stuffed mushrooms",
                            Price = 55m
                        },
                        new
                        {
                            Id = 56,
                            Description = "Roll each wrapper on the diagonal to enclose filling, folding in sides after first complete turn. Place spring rolls on prepared trays, seam-side down; brush",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Baked_spring_rolls.jpg",
                            Name = "Baked spring rolls",
                            Price = 56m
                        },
                        new
                        {
                            Id = 57,
                            Description = "This contemporary take on beef Wellington reimagines pastry-wrapped tenderloin as a tart, showcasing flavors both comforting and complex.",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Baked_spring_rolls.jpg",
                            Name = "Baked spring rolls",
                            Price = 57m
                        },
                        new
                        {
                            Id = 58,
                            Description = "Creamy pan-fried feta cheese with a golden crust is a delicious ... With the salty feta and sweet honey on top, this feta saganaki ",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Sweet_fried_saganaki.jpg",
                            Name = "Sweet fried saganaki",
                            Price = 58m
                        },
                        new
                        {
                            Id = 59,
                            Description = "If you fancy making yourself a little treat, try these tasty bacon wrapped onion rings. We replaced the traditional breadcrumbs with streaky bacon",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Bacon_rings.jpg",
                            Name = "Bacon rings",
                            Price = 59m
                        },
                        new
                        {
                            Id = 60,
                            Description = "A blooming onion, also called onion bloom, onion blossom, onion flower, bloomin' onion, or onion mum, is a dish consisting of one large onion",
                            DishGroup = 8,
                            ImgPath = "/img/menu/Blooming_onion.jpg",
                            Name = "Blooming onion",
                            Price = 60m
                        },
                        new
                        {
                            Id = 61,
                            Description = "Calzones are Italian turnovers that are stuffed with an array of ingredients. Pretty much anything that goes on a pizza can go into a calzone",
                            DishGroup = 9,
                            ImgPath = "/img/menu/CALZONES.jpg",
                            Name = "CALZONES",
                            Price = 61m
                        },
                        new
                        {
                            Id = 62,
                            Description = "Deep Fried Main Dishes. Fried chicken. Fish Tacos. Corn dogs. Finger Steaks. When you're in the mood for crispy fried food, these 5-star recipes do it right",
                            DishGroup = 9,
                            ImgPath = "/img/menu/DEEP_FRIED_MAIN_DISHES.jpg",
                            Name = "Deep Fried Main Dishes",
                            Price = 62m
                        },
                        new
                        {
                            Id = 63,
                            Description = "Ground beef or a mix of ground beef, pork and sometimes veal or venison, finely chopped (fried) onions, some broth, often with cream and sometimes with breadcrumbs soaked in milk",
                            DishGroup = 9,
                            ImgPath = "/img/menu/MEATBALLS.jpg",
                            Name = "MEATBALLS",
                            Price = 63m
                        },
                        new
                        {
                            Id = 64,
                            Description = "A pielike dish consisting of an unsweetened pastry shell filled with a custard and usually containing cheese and other ingredients, as vegetables, seafood",
                            DishGroup = 9,
                            ImgPath = "/img/menu/QUICHE.jpg",
                            Name = "QUICHE",
                            Price = 64m
                        },
                        new
                        {
                            Id = 65,
                            Description = "We've rounded up our 60 best chicken breast recipes, all of which are pretty easy, ... An easy, cheesy chicken breast supper that's as basic as they come",
                            DishGroup = 9,
                            ImgPath = "/img/menu/CHICKEN_MAIN_DISHES.jpg",
                            Name = "CHICKEN MAIN DISHES",
                            Price = 65m
                        },
                        new
                        {
                            Id = 66,
                            Description = "From seafood pastas and paellas, to creamy chowders and curries, our seafood recipes celebrate prawns, crab, clams, mussels and more.",
                            DishGroup = 9,
                            ImgPath = "/img/menu/SEAFOOD_MAIN_DISHES.jpg",
                            Name = "SEAFOOD MAIN DISHES",
                            Price = 66m
                        },
                        new
                        {
                            Id = 67,
                            Description = "Tiramisu cake is made of moist and fluffy vanilla layers soaked with a mixture of brandy, coffee liqueur and espresso",
                            DishGroup = 2,
                            ImgPath = "/img/menu/TIRAMISU_LAYER_CAKE.jpg",
                            Name = "TIRAMISU LAYER CAKE",
                            Price = 67m
                        },
                        new
                        {
                            Id = 68,
                            Description = "Devil's Food Cake is a variety of chocolate cake that uses cocoa powder instead of melted chocolate which is found in many chocolate cake recipes.",
                            DishGroup = 2,
                            ImgPath = "/img/menu/DEVIL'S_FOOD_CAKE.jpg",
                            Name = "DEVIL'S FOOD CAKE",
                            Price = 68m
                        },
                        new
                        {
                            Id = 69,
                            Description = "Lemon Soufflés are made with only three ingredients: lemons, sugar, and eggs. They are so simple but so delicous and make a big impact when served in lemon juice",
                            DishGroup = 2,
                            ImgPath = "/img/menu/LEMON_SOUFFLES.jpg ",
                            Name = "LEMON SOUFFLES",
                            Price = 69m
                        },
                        new
                        {
                            Id = 70,
                            Description = "Baklava is a layered pastry dessert made of filo pastry, filled with chopped nuts, and sweetened with syrup or honey ",
                            DishGroup = 2,
                            ImgPath = "/img/menu/BAKLAVA.jpg",
                            Name = "BAKLAVA",
                            Price = 70m
                        },
                        new
                        {
                            Id = 71,
                            Description = "Our classic 8'' doberge cakes boast six layers of rich buttermilk cake sandwiching our handmade custard, frosted with our creamy buttercream, ",
                            DishGroup = 2,
                            ImgPath = "/img/menu/LEMON_CAKE_DOBERGE.jpg ",
                            Name = "LEMON CAKE DOBERGE",
                            Price = 71m
                        },
                        new
                        {
                            Id = 72,
                            Description = "In a saucepan, combine the chocolate, milk and cream and heat on low, stirring often, until the chocolate is completely melted and the mixture ",
                            DishGroup = 2,
                            ImgPath = "/img/menu/CHOCOLATE_FONDUE.jpg ",
                            Name = "CHOCOLATE FONDUE",
                            Price = 72m
                        });
                });

            modelBuilder.Entity("Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1m,
                            DishId = 1,
                            ExpirationDate = new DateTime(2011, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Water",
                            Price = 5m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1m,
                            DishId = 2,
                            ExpirationDate = new DateTime(2011, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beer",
                            Price = 5m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1m,
                            DishId = 3,
                            ExpirationDate = new DateTime(2011, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Milk",
                            Price = 5m
                        });
                });

            modelBuilder.Entity("Data.Entities.Ingredient", b =>
                {
                    b.HasOne("Data.Entities.Dish", "Dish")
                        .WithMany("Ingredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Data.Entities.Dish", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
